server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #服务端的实例名称
  client:
    register-with-eureka: false #是否注册自己
    fetch-registry: false #如果为false,表示自己为注册中心
    service-url:
      #单击
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群 （eureka7001.com 本地 host 配置的 127.0.0.1）
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/