server:
  port: 9527

spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-zuul-9527 #修改eureka描述信息
    prefer-ip-address: true  #显示真实ip地址

info:
  app.name: kuang-springcloud

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  prefix: /kuang  #设置前缀
  ignored-services: springcloud-provider-dept  #忽视微服务id访问，只可以自己配置的访问
#  ignored-services: "*"  #隐藏全部